services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: "gunicorn rocketmancer.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    ports:
      - "8000:8000"
    networks:
      - rocketmancer-network
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    
    volumes:
      - ./nginx/rocketmancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rocketmancer-network
  
networks:
  rocketmancer-network:
    driver: bridge